apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
spec:
  serviceName: sqlserver-headless
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Release.Name }}
    spec:
      terminationGracePeriodSeconds: 30
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - name: ms-sqlserver
        command:
          - /bin/bash
          - -c
          - cp /var/opt/config/mssql.conf /var/opt/mssql/mssql.conf && /opt/mssql/bin/sqlservr
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 1433
        env:
        - name: ACCEPT_EULA
          value: "Y"
        - name: MSSQL_PID
          value: {{ .Values.mssqlPid }}
        - name: MSSQL_AGENT_ENABLED
          value: "{{ .Values.mssqlAgentEnabled }}"
        - name: SA_PASSWORD
          value: {{ required ".Values.sapassword required!" .Values.sapassword }}  
        - name: SQLCOLLATION
          value: Latin1_General_CI_AS_KS    
        volumeMounts:
        - name: {{ .Release.Name }}-mssql
          mountPath: /var/opt/mssql
        - name: {{ .Release.Name }}-config-volume
          mountPath: /var/opt/config          
        resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
      - name: {{ .Release.Name }}-config-volume
        configMap:
         name: {{ .Release.Name }}-config
  volumeClaimTemplates:
    - metadata:
       name: {{ .Release.Name }}-mssql
      spec:
       accessModes:
       - ReadWriteOnce
       resources:
        requests:
         storage: {{ .Values.persistentVolumeSize }}                     
