apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
{{- if .Values.service.annotations }}
{{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
{{- end }}
{{- end }}
spec:
  selector:
    app.kubernetes.io/name: {{ .Release.Name }}
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433
  type: {{ .Values.service.type}}