apiVersion: v1
kind: ConfigMap
metadata:
  name: definitions
  namespace: rabbitmq-system
data:
  definitions.json: |
    {
        "rabbit_version": "3.8.11",
        "rabbitmq_version": "3.8.11",
        "product_name": "RabbitMQ",
        "product_version": "3.8.11",
        "users": [
        {
            "name": "guest",
            "password_hash": "X5L0vwDQq2g8bu2Rr3oGc+uJiU+tRSFqSOj14w6zYqRK/lDU",
            "hashing_algorithm": "rabbit_password_hashing_sha256",
            "tags": "administrator",
            "limits": {}
        },
        {
            "name": "{{.Values.username}}",
            "password_hash": "{{.Values.hashedPassword}}",
            "hashing_algorithm": "rabbit_password_hashing_sha256",
            "tags": "administrator",
            "limits": {}
        }
        ],
        "vhosts": [
        {
            "name": "playground-vhost"
        },
        {
            "name": "/"
        }
        ],
        "permissions": [
        {
            "user": "guest",
            "vhost": "playground-vhost",
            "configure": ".*",
            "write": ".*",
            "read": ".*"
        },
        {
            "user": "guest",
            "vhost": "/",
            "configure": ".*",
            "write": ".*",
            "read": ".*"
        },
        {
            "user": "{{.Values.username}}",
            "vhost": "/",
            "configure": ".*",
            "write": ".*",
            "read": ".*"
        },
        {
            "user": "{{.Values.username}}",
            "vhost": "playground-vhost",
            "configure": ".*",
            "write": ".*",
            "read": ".*"
        }


        ],
        "topic_permissions": [],
        "parameters": [],
        "global_parameters": [
        {
            "name": "cluster_name",
            "value": "rabbit@A7673DD8AB36"
        },
        {
            "name": "internal_cluster_id",
            "value": "rabbitmq-cluster-id-j-A7673DD8AB36"
        }
        ],
        "policies": [],
        "queues": [
        {
            "name": "playground-quorum-queue",
            "vhost": "playground-vhost",
            "durable": true,
            "auto_delete": false,
            "arguments": {
            "x-queue-type": "quorum"
            }
        },
        {
            "name": "playground-classic-queue",
            "vhost": "playground-vhost",
            "durable": true,
            "auto_delete": false,
            "arguments": {
            "x-queue-type": "classic"
            }
        }
        ],
        "exchanges": [
        {
            "name": "playground-exchange",
            "vhost": "playground-vhost",
            "type": "fanout",
            "durable": true,
            "auto_delete": false,
            "internal": false,
            "arguments": {}
        }
        ],
        "bindings": [
        {
            "source": "playground-exchange",
            "vhost": "playground-vhost",
            "destination": "playground-quorum-queue",
            "destination_type": "queue",
            "routing_key": "",
            "arguments": {}
        },
        {
            "source": "playground-exchange",
            "vhost": "playground-vhost",
            "destination": "playground-classic-queue",
            "destination_type": "queue",
            "routing_key": "1234",
            "arguments": {}
        }
        ]
    }