apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Release.Name }}-definitions"
data:
  def.json: |
    {
      "global_parameters": [
        {
        }
      ],
      "parameters": [
        
      ],
      "permissions": [
        {
          "configure": ".*",
          "read": ".*",
          "user": "{{ .Values.username }}",
          "vhost": "/",
          "write": ".*"
        }
      ],
      "policies": [
        {
          "apply-to": "all",
          "definition": {
            {{- if .Values.mirroring.enabled }}
            "ha-mode": "exactly",
            "ha-params": 2,
            "ha-sync-mode": "automatic",
            {{- end }}
            "queue-mode": "lazy"
          },
          "name": "default",
          "pattern": ".*",
          "priority": 0,
          "vhost": "/"
        }
      ],
      "queues": [
        
      ],
      "exchanges": [
        
      ],
      "bindings": [
        
      ],
      "topic_permissions": [
        
      ],
      "users": [
        {
            "hashing_algorithm": "rabbit_password_hashing_sha256",
            "name": "{{ .Values.username }}",
            "password_hash": "{{ required "A valid .Values.hashedPassword entry required!" .Values.hashedPassword }}",
            "tags": "administrator"
        }
      ],
      "vhosts": [
        {
          "limits": [
            
          ],
          "metadata": {
            "description": "undefined",
            "tags": [
              
            ]
          },
          "name": "/"
        }
      ]
    }